{% set python_min = '3.10' %}
{% set name = "openmmdl" %}
{% set version = "1.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/wolberlab/OpenMMDL/archive/refs/tags/{{ version }}.zip
  sha256: 358ae978e1c58cb55b9020ae86bf985704fb6e047d7aba6896b3a7f3c4ed0714

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1
  
requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools >=61.0
    - sqlite >=3.40
    - versioningit
  run:
    - python >={{ python_min }}
    - numpy
    - plip
    - requests >=2.28.1
    - rdkit >=2022.03.5
    - mdtraj
    - pdbfixer
    - openff-toolkit
    - openmmforcefields
    - cuda-toolkit
    - openmm >=8.3.0
    - cuda-python >=11.7.1
    - mdanalysis >=2.3.0
    - pytest-shutil >=1.7.0
    - flask >=2.2.2
    - cairosvg
    - nglview
    - jupyter
    - ambertools
    - numba >=0.59.1

test:
  imports:
    - openmmdl
  requires:
    - pip
    - python {{ python_min }}
  commands:
    - openmmdl_simulation --help
    - openmmdl_analysis --help

about:
  home: https://github.com/wolberlab/OpenMMDL
  summary: 'Interface to OpenMM for easy setup of molecular dynamic simulations of protein-ligand complexes'
  license: MIT
  license_file: LICENSE
  doc_url: http://openmmdl.readthedocs.io/

extra:
  recipe-maintainers:
    - talagayev
    - NDoering99
