{% set name = "openmmdl" %}
{% set version = "0.9.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/wolberlab/OpenMMDL/archive/refs/tags/{{ version }}.zip
  sha256: 2504461bed6915d92fa893520a3c9a24c2a1f269112914ffe1d686f5f71a85aa

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0
  
requirements:
  host:
    - python >=3.10
    - pip
    - setuptools >=61.0
    - versioningit
  run:
    - python >=3.10
    - numpy =1.26.4
    - plip =2.3.0
    - requests >=2.28.1
    - rdkit >=2022.03.5
    - mdtraj =1.9.7
    - pdbfixer =1.8.1
    - openff-toolkit =0.16.0
    - openmmforcefields =0.11.2
    - cudatoolkit >=11.7.0
    - cuda-python >=11.7.1
    - mdanalysis >=2.3.0
    - pytest-shutil >=1.7.0
    - flask >=2.2.2
    - cairosvg =2.7.1
    - nglview =3.0.6
    - jupyter
    - ambertools =22.0
    - numba >=0.59.1

test:
  imports:
    - openmmdl
  requires:
    - pip
  commands:
    - openmmdl_simulation --help
    - openmmdl_analysis --help

about:
  home: https://github.com/wolberlab/OpenMMDL
  summary: 'Interface to OpenMM for easy setup of molecular dynamic simulations of protein-ligand complexes'
  license: MIT
  license_file: LICENSE
  doc_url: http://openmmdl.readthedocs.io/

extra:
  recipe-maintainers:
    - talagayev
    - NDoering99
