{% set name = "openmmdl" %}
{% set version = "0.9.2.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/wolberlab/OpenMMDL/archive/refs/tags/{{ version }}.zip
  sha256: 1ceb6fec3c2f1e5d67199db2d5f795a0c2da564b470af21347367c8cdce90282

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0
  
requirements:
  host:
    - python >=3.10
    - pip
    - setuptools >=61.0
    - versioningit
  run:
    - python >=3.10
    - numpy
    - plip
    - requests >=2.28.1
    - rdkit >=2022.03.5
    - mdtraj
    - pdbfixer
    - openff-toolkit
    - openmmforcefields
    - cudatoolkit >=11.7.0
    - cuda-python >=11.7.1
    - mdanalysis >=2.3.0
    - pytest-shutil >=1.7.0
    - flask >=2.2.2
    - cairosvg
    - nglview
    - jupyter
    - ambertools
    - numba >=0.59.1

test:
  imports:
    - openmmdl
  requires:
    - pip
  commands:
    - openmmdl_simulation --help
    - openmmdl_analysis --help

about:
  home: https://github.com/wolberlab/OpenMMDL
  summary: 'Interface to OpenMM for easy setup of molecular dynamic simulations of protein-ligand complexes'
  license: MIT
  license_file: LICENSE
  doc_url: http://openmmdl.readthedocs.io/

extra:
  recipe-maintainers:
    - talagayev
    - NDoering99
